cv_splits: 10 # cross validation splits
input_train_features_path: "/var/tmp/xmacko1/bachelor_thesis/repos/AndroidMalwareLabeling/data/prepared/malware_detection/train_X.csv"
input_train_target_path: "/var/tmp/xmacko1/bachelor_thesis/repos/AndroidMalwareLabeling/data/prepared/malware_detection/train_y.csv"
input_test_features_path: Null # optional csv path to test X
task_configs: # for supported keys check constants in training/api.py atm
  rf: # random forest
    output_model_path: "/var/tmp/xmacko1/bachelor_thesis/repos/AndroidMalwareLabeling/results/models/malware_detection/rf.joblib" # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
